### ISSUE TITLE
Trying to build on Linux

### ISSUE THREAD

**Issue by prokoudine** [OGRECave/spacescape#1]
CMake Error at CMakeLists.txt:23 (FIND_PACKAGE):
  By not providing "FindOGRE.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OGRE", but
  CMake did not find one.

  Could not find a package configuration file provided by "OGRE" with any of
  the following names:

    OGREConfig.cmake
    ogre-config.cmake

  Add the installation prefix of "OGRE" to CMAKE_PREFIX_PATH or set
  "OGRE_DIR" to a directory containing one of the above files.  If "OGRE"
  provides a separate development package or SDK, be sure it has been
  installed.

I have Ogre 1.9 installed on Debian Unstable with the dev package. All the headers are in /usr/include/OGRE. I tried setting that dir for OGRE_DIR in cmake-gui, but cmake-gui still changes it to "OGRE_DIR-NOTFOUND".

What do I need to do?

**Comment by paroj** [comment]
this needs Ogre 1.10+
